#!/usr/bin/env bash
go get github.com/99designs/gqlgen@v0.17.31 
go get github.com/99designs/gqlgen/internal/imports@v0.17.31 
go get github.com/99designs/gqlgen/codegen/config@v0.17.31
go generate ./...
